### ISSUE TITLE
Generalization with less data experiment

### ISSUE THREAD

**Issue by dbtmpl** [ucbdrive/ShapeProp#2]
Hi,

first of all, really nice work! I very much enjoyed reading it.

I'm working on a similar topic and wonder if you also uploaded the code for your experiment "Generalization with less data", shown in figure 6 of your work. I looked through your code but could not find it ad-hoc.

Best,
David,

**Comment by dbtmpl** [comment]
I ended up implementing it myself now. In the end it was way less tedious than I expected it to be :)

**Comment by jingtingxu369** [comment]
Hi，
Did you report an “RuntimeError: cuda runtime error (10) : invalid device ordinal at ../torch/csrc/cuda/Module.cpp:33”error when you ran the program？

 How do you fix this?

Thanks
